In [1]:
import numpy as np

In [2]:
print(np.__version__)
np.show_config()

1.16.2
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Program Files/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Program Files/Anaconda\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Program Files/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\l

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [6]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [12]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [16]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.56427637 0.45412204 0.50304108]
  [0.21907532 0.62509612 0.82134526]
  [0.21429706 0.83363732 0.01060917]]

 [[0.41238046 0.97137928 0.11567628]
  [0.17724033 0.78716479 0.26072043]
  [0.0030698  0.40326985 0.24741403]]

 [[0.64690922 0.02279276 0.03952369]
  [0.63902528 0.7163267  0.9948127 ]
  [0.2300646  0.27435439 0.37067291]]]


In [23]:
z = np.random.random((10,10))
zmin,zmax = z.min(),z.max()
print(zmin,zmax)

0.0026874536696441798 0.991648403411027


In [24]:
z = np.random.random(30)
m = np.mean(z)
print(m)

0.47961635255819346


In [25]:
z = np.ones((10,10))
z[1:-1,1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [29]:
z = np.ones((5,5))
z = np.pad(z,pad_width=1,mode='constant',constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [30]:
0*np.nan

nan

In [31]:
np.nan == np.nan

False

In [32]:
np.inf > np.nan

False

In [33]:
np.nan - np.nan

nan

In [34]:
0.3 == 3*0.1

False

In [38]:
z = np.diag(1+np.arange(4),k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [39]:
z = np.zeros((8,8), dtype = int)
z[1::2,::2]=1
z[::2,1::2]=1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [42]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [43]:
z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [50]:
z = np.random.random((5,5))
zmax,zmin=z.max(),zmin
z=(z-zmin)/(zmax-zmin)
print(z)

[[0.87850534 0.40271772 0.81420063 0.83184065 0.81753286]
 [0.07226815 0.24777198 0.63189403 0.16927092 0.12052892]
 [0.74552577 0.73534933 0.80771712 0.1536456  0.05553531]
 [0.65978655 0.37555236 0.79046262 0.95228462 0.55856529]
 [0.29573181 0.91709432 0.24409008 0.08188738 1.        ]]


In [51]:
color = np.dtype([("r",np.ubyte,1),
                  ("g",np.ubyte,1),
                  ("b",np.ubyte,1),
                  ("a",np.ubyte,1),])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [52]:
z = np.dot(np.ones((5,3)),np.ones((3,2)))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [54]:
z = np.arange(11)
z[(3<z)&(z<=8)]*=-1
print(z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [55]:
print(sum(range(5),-1))

9


In [57]:
from numpy import *
print(sum(range(5),-1))

10


In [59]:
print(np.array(0)/np.array(0))

nan


D:\Program Files\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [60]:
print(np.array(0)//np.array(0))

0


D:\Program Files\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [61]:
print(np.array([np.nan]).astype(int).astype(float))

[-2.14748365e+09]


In [64]:
z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(z)),z))

[ 7.  5. 10. -9. -5. -3.  4. -9. -6. -6.]


In [65]:
z1 = np.random.randint(0,10,10)
z2 =np.random.randint(0,10,10)
print(np.intersect1d(z1,z2))

[0 3 4 8]


In [66]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-08-09
Today is 2019-08-10
Tomorrow is 2019-08-11


In [67]:
z= np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [68]:
z = np.zeros((5,5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [72]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [73]:
z = np.linspace(0,1,11,endpoint=False)[1:]
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [74]:
z = np.random.random(10)
z.sort()
print(z)

[0.03832426 0.07469098 0.19254235 0.2021088  0.33302382 0.41156564
 0.50328473 0.84422089 0.89579024 0.95029529]


In [76]:
z = np.arange(10)
np.add.reduce(z)

45

In [77]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [79]:
z =np.zeros(10)
z.flags.writeable = False
z[0]=1

ValueError: assignment destination is read-only

In [82]:
z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)  
T = np.arctan2(Y,X)
print (R)
print (T)

[0.67508339 0.37700434 0.47656321 0.79669432 0.89087283 1.17392628
 0.5954815  0.28703041 0.74884891 0.64610386]
[0.95431929 0.61133465 0.44078183 0.5896994  0.52840136 0.99173636
 1.12130539 0.72028191 1.2078801  0.43301929]


In [84]:
z = np.random.random(10)
z[z.argmax()] = 1 
print (z)

[0.37134994 0.56150603 0.44127657 0.49855474 0.2887474  1.
 0.47711335 0.17738467 0.84441904 0.79690957]


In [85]:
z = np.zeros((5,5),[('x',float),('y',float)])
z['x'],z['y'] = np.meshgrid(np.linspace(0,1,5),
                            np.linspace(0.1,5))
print(z)

ValueError: could not broadcast input array from shape (50,5) into shape (5,5)

In [86]:
x= np.arange(8)
y = x + 0.5
c = 1.0 /np.subtract.outer(x,y)
print(np.linalg.det(c))

3638.1636371179666


In [94]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [102]:
z = np.ser_printtoptions(threshold=np.nan)
z = np.zeros((16,16))
print(z)

AttributeError: module 'numpy' has no attribute 'ser_printtoptions'

In [96]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

36
